### ISSUE TITLE
[FEATURE] Enhancement of payment methods of Worldline

### ISSUE THREAD

**Issue by AnandKGanesh** [juspay/hyperswitch#1016]
### Feature Description

Support for Worldline processor

Tasks checklist:

- [ ] Webhooks (refunds, disputes)
- [ ] Bank redirects (IDeal, Giropay, Sofort)

### Possible Implementation

Covered under sub-issues

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None
