### ISSUE TITLE
[REFACTOR] Use a single Docker image across integration test, sandbox and production environments

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#1346]
### Description

As of now, we have two `cargo` features, `sandbox` and `production`, which are deployed in the respective environments. Moving forward, we'd prefer having a single feature called `release`, which can be deployed in our integration test, sandbox and production environments. This would increase our confidence that the exact same code is running in all three environments.

The tasks involved in this effort are as follows (mostly in order of dependency):

- [ ] Remove the `pii-encryption-script` feature
- [ ] Unify the `sandbox` and `production` features (this would also need corresponding Dockerfile and CI workflow changes)
- [ ] Optionally, add an enum variant for the `Environment` enum corresponding to our integration test environment

As a continuation of this issue, all features (S3 integration, KMS integration, email integration, etc.) can be enabled/disabled with runtime toggles only, instead of using `cargo` features.

**Comment by SanchithHegde** [comment]
Closing this as completed: won't be taking up the addition of a new enum variant for the integration test environment.
