### ISSUE TITLE
docs(CONTRIBUTING): add information about tests and community links

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#14]
This issue serves an extension of #9; the following pieces of information are yet to be added to the [contributing guidelines](https://github.com/juspay/orca/blob/4ce86afd4e00a036eba9b70916b4880a049e4d9f/contrib/CONTRIBUTING.md):

- [ ] Tests
- [ ] Versioning policy
- [ ] Release process
- [x] Links to Discord/Slack communities #310
	- [x] Also add them to [issue template `config.yml`](https://github.com/juspay/orca/blob/3e0298032b5c9535d418f50ab440a4aeaf265aba/.github/ISSUE_TEMPLATE/config.yml)
- [ ] Process to bump MSRV (Optional)

I'll briefly jot down what I feel are necessary with respect to each of the items.

## Tests

- Specify what type of changes require tests. Example: new features, bug fixes, connector integrations, etc.
- Specify where to place unit/integration/documentation/API tests. (Of course documentation tests would be alongside documentation.)
- Specify how to run tests, especially when external tools are involved (anything other than `cargo`).

## Versioning Policy

- It would be better if we can provide certain guarantees to the users of our APIs, that our APIs won't change behavior between certain types of releases.
- Specify what changes can be expected between major, minor and patch releases.
- If possible, try to follow SemVer strictly.

## Release Process

- This is targeted primarily at maintainers, but aims to serve as a checklist to refer to before publishing releases.
- List out each of the steps in detail. These could include:
	- Bumping up versions
	- Updating Cargo metadata
	- Updating links on documentation pages
	- Updating changelog files
	- Review changes
	- Open PR
	- Release

Now that I think of the release process, I'm wondering if we should also document the steps to take when bumping up MSRV.

## Links to Discord/Slack communities

- As of now, users can use the GitHub Discussions space on our repository to interact with the project maintainers. But a more organized space is necessary; two of the potential candidates are a Discord server and a Slack workspace.
- Both of these spaces exist as of creating this issue, but require a bit of "initial setup" before people can be invited in there.

**Comment by SanchithHegde** [comment]
Closing this, I think this issue is stale at this point.
