### ISSUE TITLE
refactor(disputes): modularize disputes functionality

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#1607]
The overall goal of this is to split disputes functionality in to a self-contained module...
With minimal coupling from the rest of the modules
This could be broken down into a similar manner as #1579 

- [ ] Scoped error enums
- [ ] refactoring related core files
- [ ] refactor utils & related helpers for this
- [ ] Mirror the updated structure to api models
- [ ] Mirror the updated structure to storage/diesel models
