### ISSUE TITLE
feat(db): Implement interfaces for `MockDb`

### ISSUE THREAD

**Issue by NishantJoshi00** [juspay/hyperswitch#172]
## Description

This issue's primary focus lies in implementing the pending interface functionality for [`MockDb`](https://github.com/juspay/hyperswitch/blob/f624eb52d61561c365cce21e58b08281d096d904/crates/router/src/db.rs#L79). The purpose of this change is to have a simple and effective mechanism for testing without connecting to any outside entity for the storage need. The `MockDb` will come in play for unit tests, integration tests, etc.

## Interfaces to implement

- [x] #954
- [x] #996
- [x] #1189
- [x] #997
- [ ] Implement `ConnectorResponseInterface` for `MockDb` (partially complete)
- [ ] Implement `CustomerInterface` for `MockDb` (partially complete)
- [x] #1190
- [x] #1191
- [x] #1116 
- [x] #1257
- [x] #1256
- [x] #2438
- [x] #1123
- [ ] #1329
- [ ] Implement `PaymentIntentInterface` for `MockDb` (partially complete)
- [x] #1491
- [ ] #4150
- [ ] Implement `ProcessTrackerInterface` for `MockDb` (partially complete)
- [ ] #1490
- [x] #1276
- [x] #1115 
- [x] #1697 
- [x] #2039
- [ ] Implement BatchSampleDataInterface for `MockDb` 
- [x] https://github.com/juspay/hyperswitch/issues/3044
- [ ]  Implement  `GenericLink` for `MockDb`.

If you're interested in picking up any item from the list, please let us know. We'll spin out an issue and assign it to you.

**Comment by SanchithHegde** [comment]
@jeevaprakashdr I've spin out #954 from this issue. Please comment on the issue thread so that I can assign it to you.

**Comment by younes-io** [comment]
I would like to implement the `RefundInterface`

**Comment by SanchithHegde** [comment]
@younes-io I've spin out #1276 for the same. Please comment on the issue thread so that I can assign it to you.

**Comment by younes-io** [comment]
Willing to work on `PaymentAttemptInterface`

**Comment by SanchithHegde** [comment]
> Willing to work on `PaymentAttemptInterface`

@younes-io I've created #1329, please comment on the thread so that I can assign it to you.

**Comment by dalprahcd** [comment]
Hello @SanchithHegde, I would like to help by implementing the missing implementation of `MockDb` for `MerchantAccountInterface`

**Comment by SanchithHegde** [comment]
Sure @dalprahcd, I've created #2438 for the same. Please comment on the issue, so that it can be assigned to you.
