### ISSUE TITLE
[FEATURE] Vaulting a payment method

### ISSUE THREAD

**Issue by tinu-hareesswar** [juspay/hyperswitch#3696]
### Feature Description

This will be the tracking issue for all Vaulting related changes.

### Problem Statement
https://juspay.atlassian.net/wiki/spaces/JR/pages/2260566162/Vaulting+and+Tokenization+with+Hyperswitch

### Use Cases
![Screenshot 2024-02-19 at 2 16 05 PM](https://github.com/juspay/hyperswitch/assets/11926525/601f5ef0-078e-4bda-821b-2db429e7455c)

### Sequence Diagrams
https://docs.google.com/document/d/1Ox0JaOCtmhSLLxSc-OT7AdqRovzpXSxdaoODJ4LH7O4/edit?usp=sharing

### Task Distribution

API Changes
- [ ] Payment Methods API updates for vaulting
- [ ] Payments API changes for vaulting

Flow Changes
- [ ] Connector Integration for vaulting
- [ ] Payments confirm changes for MITs
- [ ] Payment Methods confirm flow 

DB Changes
- [ ] Payment Methods Table
- [ ] Payment Intent
- [ ] Client Secret
- [ ] Business Profile
 

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by shubham-chhimpa** [comment]
not able to open both these links. Only people having access can open it.

https://juspay.atlassian.net/wiki/spaces/JR/pages/2260566162/Vaulting+and+Tokenization+with+Hyperswitch

https://docs.google.com/document/d/1Ox0JaOCtmhSLLxSc-OT7AdqRovzpXSxdaoODJ4LH7O4/edit?usp=sharing

**Comment by tinu-hareesswar** [comment]
@shubham-chhimpa - sorry these were internal docs that were linked for dev assistance, I've removed it now. Will add relevant details here.

**Comment by luizaraujobliver** [comment]
@tinu-hareesswar This internal developer assistance document would help us a lot, without a doubt. Can't share?
