### ISSUE TITLE
[FEATURE] Routing V2 APIs

### ISSUE THREAD

**Issue by vspecky** [juspay/hyperswitch#5049]
### Feature Description

This will serve as the tracking issue for all tasks revolving around all Routing API changes required for Hyperswitch 2.0

### Tasks
- [ ] Refactor Routing endpoints to include descriptive paths and resource IDs wherever required as per guidelines
- [ ] Add a `status` column to the `routing_algorithm` table to be used for soft deletes
- [ ] Add API support for updating a routing algorithm
- [ ] Add a column to the `business_profiles` table for the fallback connector list, and move the same to the new column from the configs table.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else
