### ISSUE TITLE
[FEATURE] Nexinets support for auth & capture, bank redirects and paypal

### ISSUE THREAD

**Issue by manojradhakrishnan** [juspay/hyperswitch#938]
### Feature Description

- [x] Authorize, Capture, Void ThreeDS and non ThreeDS cards #898
- [x] Bank redirects : ideal, sofort, eps and Giropay #898
- [x] Wallet : Paypal redirection #898
- [x] Refund, Psync and Rsync #898

### Possible Implementation

Not applicable

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by srujanchikke** [comment]
closing as completed in #898
