### ISSUE TITLE
[FEATURE] Forte support for card payments

### ISSUE THREAD

**Issue by manojradhakrishnan** [juspay/hyperswitch#946]
### Feature Description

Scope:

- [x] Template connector code #854 
- [x] Cards Non 3DS flows #955
- [x] Refunds #955

### Possible Implementation

Not applicable

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by prasunna09** [comment]
closing this as all the above mentioned tasks are done.
