### ISSUE TITLE
[FEATURE] Add Support for Paypal payment processor

### ISSUE THREAD

**Issue by AnandKGanesh** [juspay/hyperswitch#969]
### Feature Description

Support for Paypal processor

Tasks checklist:

- [x] Cards Non-3DS
- [ ] Cards 3DS - Blocked on Paypal
- [x] Wallets (Apple Pay, Google Pay, Paypal)
- [x] Refunds
- [x] [Webhooks (Refunds, Payments, Disputes) ](https://github.com/juspay/hyperswitch/pull/2003)
- [x] #1066

### Possible Implementation

Covered under sub-issues 

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by prasunna09** [comment]
Closing this as all features for PayPal is merged and tested except 3DS as it is blocked on connector side
